[tool.poetry]
name = "RixLint"
version = "1.0"
description = ""
authors = ["rix.tmp"]

[tool.poetry.dependencies]
python = ">=3.8.0,<3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"